#!/usr/bin/env bash
# skyMem one-command installer.
#
# Usage:
#   ./install.sh                      # personal-PA mode, prompts for keys + WhatsApp
#   ./install.sh --demo               # demo mode, no real data, sample persona
#   ./install.sh --mode=builder --project-root=/path/to/project
#                                     # AI engineering context, no WhatsApp
#   ./install.sh --skip-keys          # don't prompt for keys (assumes .env exists)
#
# What it does:
#   1. Checks Docker is running + 16GB RAM available
#   2. Prompts for Anthropic + Cohere API keys (or reads from env)
#   3. Writes .env
#   4. Builds + starts the docker-compose stack
#   5. For PA mode: walks through WhatsApp Baileys QR pairing
#   6. For demo mode: ingests sample data + extracts sample persona
#   7. Prints next-steps URL

set -u

# ── Args ───────────────────────────────────────────────────────────────────
MODE="pa"
DEMO=0
SKIP_KEYS=0
PROJECT_ROOT=""

for arg in "$@"; do
  case "$arg" in
    --demo)               DEMO=1 ;;
    --mode=*)             MODE="${arg#--mode=}" ;;
    --project-root=*)     PROJECT_ROOT="${arg#--project-root=}" ;;
    --skip-keys)          SKIP_KEYS=1 ;;
    --help|-h)
      sed -n 's/^# //p' "$0" | head -25
      exit 0
      ;;
  esac
done

if [ "$DEMO" -eq 1 ]; then MODE="demo"; fi

echo "==========================================="
echo "  skyMem installer  —  mode: $MODE"
echo "==========================================="
echo ""

# ── Preflight ──────────────────────────────────────────────────────────────
echo "→ Checking prerequisites..."

if ! command -v docker >/dev/null 2>&1; then
  echo "✗ Docker not found. Install Docker Desktop / Docker Engine first: https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  echo "✗ Docker daemon not running. Start Docker Desktop and re-run."
  exit 1
fi

# Memory check (best-effort, platform-dependent)
if command -v sysctl >/dev/null 2>&1; then
  MEM_BYTES=$(sysctl -n hw.memsize 2>/dev/null || echo 0)
elif [ -f /proc/meminfo ]; then
  MEM_KB=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
  MEM_BYTES=$((MEM_KB * 1024))
else
  MEM_BYTES=0
fi
if [ "$MEM_BYTES" -gt 0 ]; then
  MEM_GB=$((MEM_BYTES / 1024 / 1024 / 1024))
  if [ "$MEM_GB" -lt 12 ]; then
    echo "⚠  Only ${MEM_GB}GB system RAM detected. skyMem needs ~16GB Docker headroom."
    echo "   You can continue but performance will degrade. Consider a cloud VM."
  else
    echo "✓ System RAM: ${MEM_GB}GB"
  fi
fi
echo "✓ Docker daemon healthy"
echo ""

# ── Keys ───────────────────────────────────────────────────────────────────
if [ "$SKIP_KEYS" -eq 0 ] && [ "$MODE" != "demo" ]; then
  echo "→ API keys"
  echo ""

  if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
    echo "  Anthropic API key (used for Sonnet/Haiku LLM calls)."
    echo "  Get one at https://console.anthropic.com/"
    read -r -p "  ANTHROPIC_API_KEY: " ANTHROPIC_API_KEY
  fi

  if [ -z "${COHERE_API_KEY:-}" ]; then
    echo ""
    echo "  Cohere API key (used for embeddings + reranking — free tier OK to start)."
    echo "  Get one at https://dashboard.cohere.com/"
    read -r -p "  COHERE_API_KEY: " COHERE_API_KEY
  fi

  if [ -z "$ANTHROPIC_API_KEY" ] || [ -z "$COHERE_API_KEY" ]; then
    echo "✗ Both keys required. Re-run with the keys exported, or paste them when prompted."
    exit 1
  fi
else
  ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-demo-no-key}"
  COHERE_API_KEY="${COHERE_API_KEY:-demo-no-key}"
fi

# ── Write .env ─────────────────────────────────────────────────────────────
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
  echo "→ .env already exists — leaving it alone (re-run with --skip-keys to skip key prompt)"
else
  echo "→ Writing $ENV_FILE..."
  cat > "$ENV_FILE" <<EOF
# skyMem configuration — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Database
DATABASE_URL="mysql://root:skypassword@localhost:3306/office_space?connection_limit=20"

# LLM keys
ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY"
COHERE_API_KEY="$COHERE_API_KEY"

# Embedding provider — Cohere v3 (1024d, retrieval-tuned)
SKY_EMBED_PROVIDER=cohere

# Reranker
SKY_RERANK_PROVIDER=cohere

# Mode
SKY_MODE=$MODE

# Auth: api_key (production default since 2026-05-08)
SKY_CLAUDE_AUTH_MODE=api_key

# Optional: Phase 1 scope filter (default on)
SKY_PHASE1_SCOPE=true

# Optional: Ollama for local cheap LLM (used by some bg tasks)
OLLAMA_URL=http://host.docker.internal:11434
EOF
  chmod 600 "$ENV_FILE"
  echo "✓ Wrote $ENV_FILE"
fi
echo ""

# ── Project root for builder mode ──────────────────────────────────────────
if [ "$MODE" = "builder" ] && [ -z "$PROJECT_ROOT" ]; then
  echo "→ Builder mode requires --project-root=/path/to/your/project"
  echo "  Re-run with the flag set."
  exit 1
fi

if [ "$MODE" = "builder" ]; then
  echo "PROJECTS_ROOT=$PROJECT_ROOT" >> "$ENV_FILE"
fi

# ── Build + start ──────────────────────────────────────────────────────────
echo "→ Building containers..."
docker compose build 2>&1 | tail -10
echo ""

echo "→ Starting MySQL + skyMem stack..."
docker compose up -d
sleep 5

# Wait for healthy
echo -n "→ Waiting for sky-bridge to be healthy"
for i in $(seq 1 60); do
  if docker inspect sky-bridge --format '{{.State.Health.Status}}' 2>/dev/null | grep -q healthy; then
    echo " ✓"
    break
  fi
  echo -n "."
  sleep 2
done
echo ""

# ── Schema migration ───────────────────────────────────────────────────────
echo "→ Applying schema..."
docker exec sky-bridge sh -c 'cd /app && npx prisma db push --skip-generate --accept-data-loss' 2>&1 | tail -3
docker exec sky-bridge sh -c 'cd /app && npx prisma generate' 2>&1 | tail -2
echo ""

# ── Mode-specific bootstrap ────────────────────────────────────────────────
case "$MODE" in
  pa)
    echo "==========================================="
    echo "  WhatsApp pairing"
    echo "==========================================="
    echo ""
    echo "Open WhatsApp on your phone → Settings → Linked Devices → Link a Device."
    echo "A QR code will print below in ~10 seconds."
    echo ""
    echo "Watch the live log with:"
    echo "  docker logs -f sky-bridge"
    echo ""
    echo "Once paired, every message you send Sky gets ingested + extracted."
    echo "First persona facts will land in ~5 min."
    ;;
  demo)
    echo "==========================================="
    echo "  Demo mode bootstrap"
    echo "==========================================="
    echo ""
    echo "→ Loading sample data..."
    docker exec sky-bridge sh -c 'export DATABASE_URL=$(echo "$DATABASE_URL" | sed -e "s|@localhost:|@host.docker.internal:|g") && node /app/scripts/load-demo-data.js' 2>&1 | tail -10
    echo ""
    echo "Demo ready. Try chatting at:"
    echo "  http://localhost:3002/"
    ;;
  builder)
    echo "==========================================="
    echo "  Builder mode bootstrap"
    echo "==========================================="
    echo ""
    echo "→ Ingesting project at $PROJECT_ROOT..."
    docker exec sky-bridge sh -c "export DATABASE_URL=\$(echo \"\$DATABASE_URL\" | sed -e 's|@localhost:|@host.docker.internal:|g') && node /app/scripts/ingest-project.js --root=$PROJECT_ROOT" 2>&1 | tail -15
    echo ""
    echo "Project ingested. Configure your AI tool (Claude Code / Cursor) to use the"
    echo "skyMem MCP server at http://localhost:3002/mcp"
    ;;
esac

echo ""
echo "==========================================="
echo "  Install complete"
echo "==========================================="
echo ""
echo "  Dashboard: http://localhost:3002/"
echo "  Logs:      docker logs -f sky-bridge"
echo "  Bench:     docker exec sky-bridge bash /app/scripts/run-locomo-sequential.sh"
echo "  Stop:      docker compose down"
echo ""
echo "Read SKY-REBUILD.md for the architecture deep-dive."
